runtime: nodejs12

instance_class: F2

handlers:
- url: /api.*
  script: auto

- url: /(.*\.(gif|png|jpg|css|js|svg|mp4|json|ico|woff2)(|\.map))$
  static_files: static/\1
  upload: static/(.*)(|\.map)
  http_headers:
    test-header: did it work

- url: /.*
  static_files: static/index.html
  upload: static/index.html

env_variables:
  production: true